### PR TITLE
changes site

### PR DESCRIPTION
**Pull request by mbeylin**

### CODE REVIEW

**Comment by mbeylin** [comment]
@andytudhope this is probably the worst webdev experience of my life but I think I've hacked it together. All of the styling that I changed on any of the iframe components was done directly to the minified code, so those original codebases will still include the crappy styling

**Comment by andytudhope** [comment]
Well, I feel nothing for the webdev of changing minified code, as that was not the intention :stuck_out_tongue_winking_eye:  

As I said via email, you just need to change [this repo](https://github.com/andytudhope/mm-leaderboard), build it and transfer files across. Not ideal, I admit, but what's a poor English Lit person to do :angel: 

One question: I don't really like the new colour of the leaderboard to be honest. What was your thinking there? Why not just keep the same purple as the rest of the site? Happy that you changed the font - that was all Mariano last year :wink: 

Other than that, thank you SO MUCH, I love you long time, and you are generally the best :heart:

**Comment by mbeylin** [comment]
Re: the leaderboard and the changed styling in general, I wanted the design to not be so bright purple / bounties related, and instead make it a more colour neutral theme. The leaderboard design was just my MVP implementation of that new color scheme, but I'm mostly ambivalent with regards to other implementations (as long as they aren't that bright purple)

**Comment by andytudhope** [comment]
OK, will merge here and make some changes to the purple to offend my bae less :stuck_out_tongue_winking_eye:

**Comment by mbeylin** [comment]
😍

**Pull request merged**
